# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f50fce874736d3bf28a5c7ec04ca6adcfd0a545f29330cc2ab54cd391db98fb42736dd3fdb2132ef49668b542eb939e8ce34c2d544eedcb8246bb2a07f3abcd

test:
  secret_key_base: 900baf29defc206606e39eec9e216b875dbbb6d18451fb19b1ff379fe4582d0f93053e642c0965b7b569d273c86707385cc44ecf2c8fbaa06adc2505bc8ce38d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
